// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3c1f0fab-2102-4015-945c-b99ee095deb3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_truoii5cs",
    "aws_user_pools_web_client_id": "72l57on0b68enkqippgdad0f7p",
    "oauth": {}
};


export default awsmobile;
